/**
 * 🗄️ AutoMigrationCard
 * User-friendly database migration card with real-time progress
 */
import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { 
  Database, 
  Sparkles, 
  Check, 
  X, 
  ChevronDown, 
  ChevronUp,
  Shield,
  Zap,
  HardDrive,
  Lock,
  Trophy,
  Users,
  MessageSquare,
  Star
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { ScrollArea } from "@/components/ui/scroll-area";
import { MigrationProgressSteps } from "./MigrationProgressSteps";
import type { PendingMigration } from "@/hooks/useUnifiedOrchestrator";

interface AutoMigrationCardProps {
  migration: PendingMigration;
  onApprove: () => void;
  onReject: () => void;
  isProcessing?: boolean;
}

// Feature icon mapping
const FEATURE_ICONS: Record<string, { icon: React.ElementType; label: string }> = {
  'leaderboard': { icon: Trophy, label: 'Лидерборд' },
  'achievements': { icon: Star, label: 'Достижения' },
  'profiles': { icon: Users, label: 'Профили' },
  'user_progress': { icon: Zap, label: 'Прогресс' },
  'chat': { icon: MessageSquare, label: 'Чат' },
  'notifications': { icon: Sparkles, label: 'Уведомления' },
  'file_upload': { icon: HardDrive, label: 'Файлы' },
  'scores': { icon: Trophy, label: 'Очки' },
  'avatars': { icon: Users, label: 'Аватары' },
};

export function AutoMigrationCard({
  migration,
  onApprove,
  onReject,
  isProcessing = false,
}: AutoMigrationCardProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [showProgress, setShowProgress] = useState(false);
  
  const isAutoGenerated = migration.autoGenerated;
  const tables = migration.tables || [];
  const features = migration.features || [];
  const isExecuting = migration.status === 'executing' || isProcessing;
  const isCompleted = migration.status === 'completed';
  const isFailed = migration.status === 'failed';
  
  // Show progress when executing or completed
  const shouldShowProgress = isExecuting || isCompleted || isFailed;
  
  // Get user-friendly description
  const getDescription = () => {
    if (migration.description) {
      // Remove technical prefixes
      return migration.description
        .replace(/^🤖\s*AI-рекомендация:\s*/i, '')
        .replace(/^AI рекомендация:\s*/i, '');
    }
    
    if (tables.length === 1) {
      return `Создаю хранилище для ${getTablePurpose(tables[0])}`;
    }
    
    if (tables.length > 1) {
      return `Настраиваю ${tables.length} таблицы для вашего приложения`;
    }
    
    return 'Подготавливаю базу данных для вашего приложения';
  };
  
  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      className="w-full"
    >
      <Card className="border-primary/30 bg-gradient-to-br from-primary/5 to-background overflow-hidden">
        <CardHeader className="pb-3">
          <div className="flex items-start justify-between gap-4">
            <div className="flex items-center gap-3">
              <motion.div 
                className="p-2 rounded-lg bg-primary/10"
                animate={isExecuting ? { 
                  scale: [1, 1.1, 1],
                  transition: { repeat: Infinity, duration: 1.5 }
                } : {}}
              >
                <Database className="w-5 h-5 text-primary" />
              </motion.div>
              <div>
                <CardTitle className="text-lg flex items-center gap-2 flex-wrap">
                  {isExecuting ? 'Настраиваю базу данных...' : 
                   isCompleted ? 'База данных готова!' :
                   isFailed ? 'Ошибка настройки' :
                   'Настройка базы данных'}
                  {isAutoGenerated && !isExecuting && !isCompleted && (
                    <Badge 
                      variant="secondary" 
                      className="bg-primary/20 text-primary border-primary/30"
                    >
                      <Sparkles className="w-3 h-3 mr-1" />
                      AI-рекомендация
                    </Badge>
                  )}
                </CardTitle>
                <p className="text-sm text-muted-foreground mt-1">
                  {getDescription()}
                </p>
              </div>
            </div>
            
            <div className="flex items-center gap-2 flex-shrink-0">
              {migration.status === 'pending' && !isProcessing && (
                <>
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={onReject}
                    className="border-destructive/50 text-destructive hover:bg-destructive/10"
                  >
                    <X className="w-4 h-4 mr-1" />
                    Пропустить
                  </Button>
                  <Button
                    size="sm"
                    onClick={onApprove}
                    className="bg-gradient-to-r from-primary to-primary/80"
                  >
                    <Check className="w-4 h-4 mr-1" />
                    Создать
                  </Button>
                </>
              )}
              
              {isExecuting && (
                <Badge variant="outline" className="bg-primary/10 text-primary border-primary/30 animate-pulse">
                  <Database className="w-3 h-3 mr-1 animate-spin" />
                  Выполняется...
                </Badge>
              )}
              
              {isCompleted && (
                <motion.div
                  initial={{ scale: 0 }}
                  animate={{ scale: 1 }}
                  transition={{ type: "spring", stiffness: 500, damping: 25 }}
                >
                  <Badge variant="default" className="bg-accent/20 text-accent-foreground border-accent/30">
                    <Check className="w-3 h-3 mr-1" />
                    Готово!
                  </Badge>
                </motion.div>
              )}
              
              {isFailed && (
                <Badge variant="destructive">
                  <X className="w-3 h-3 mr-1" />
                  Ошибка
                </Badge>
              )}
            </div>
          </div>
        </CardHeader>
        
        <CardContent className="pt-0 space-y-4">
          {/* What you'll get section */}
          {!shouldShowProgress && (
            <div className="space-y-3">
              <p className="text-xs font-medium text-muted-foreground uppercase tracking-wide">
                Что будет создано:
              </p>
              <div className="flex flex-wrap gap-2">
                {tables.map((table) => (
                  <Badge 
                    key={table}
                    variant="outline" 
                    className="bg-primary/10 text-primary border-primary/30"
                  >
                    <Database className="w-3 h-3 mr-1" />
                    {getTableFriendlyName(table)}
                  </Badge>
                ))}
                
                {migration.requiresAuth && (
                  <Badge variant="outline" className="bg-secondary/50 text-secondary-foreground border-secondary">
                    <Lock className="w-3 h-3 mr-1" />
                    Авторизация
                  </Badge>
                )}
                
                {features.map((feature) => {
                  const config = FEATURE_ICONS[feature];
                  if (!config) return null;
                  const Icon = config.icon;
                  return (
                    <Badge 
                      key={feature}
                      variant="outline" 
                      className="bg-accent/10 text-accent-foreground border-accent/30"
                    >
                      <Icon className="w-3 h-3 mr-1" />
                      {config.label}
                    </Badge>
                  );
                })}
                
                {/* Always show security */}
                <Badge variant="outline" className="bg-muted text-muted-foreground border-border">
                  <Shield className="w-3 h-3 mr-1" />
                  Защита данных
                </Badge>
              </div>
            </div>
          )}
          
          {/* Real-time progress */}
          <AnimatePresence>
            {shouldShowProgress && (
              <MigrationProgressSteps
                sql={migration.sql}
                tables={tables}
                features={features}
                isExecuting={isExecuting}
                result={migration.result}
              />
            )}
          </AnimatePresence>
          
          {/* Error message */}
          {isFailed && migration.result?.message && (
            <motion.div
              initial={{ opacity: 0, y: 10 }}
              animate={{ opacity: 1, y: 0 }}
              className="p-3 rounded-lg bg-destructive/10 border border-destructive/20"
            >
              <p className="text-sm text-destructive">
                {migration.result.message}
              </p>
            </motion.div>
          )}
          
          {/* Technical details toggle (for developers) */}
          <button
            onClick={() => setIsExpanded(!isExpanded)}
            className="flex items-center gap-2 text-xs text-muted-foreground hover:text-foreground transition-colors"
          >
            {isExpanded ? (
              <ChevronUp className="w-3 h-3" />
            ) : (
              <ChevronDown className="w-3 h-3" />
            )}
            {isExpanded ? 'Скрыть детали' : 'Показать детали (для разработчиков)'}
          </button>
          
          <AnimatePresence>
            {isExpanded && (
              <motion.div
                initial={{ height: 0, opacity: 0 }}
                animate={{ height: 'auto', opacity: 1 }}
                exit={{ height: 0, opacity: 0 }}
                transition={{ duration: 0.2 }}
                className="overflow-hidden"
              >
                <ScrollArea className="h-48 rounded-lg border border-border bg-muted/30">
                  <pre className="p-3 text-[10px] font-mono text-muted-foreground whitespace-pre-wrap">
                    {migration.sql}
                  </pre>
                </ScrollArea>
                
                <div className="flex items-center gap-2 mt-2 text-[10px] text-muted-foreground">
                  <Shield className="w-3 h-3 text-primary" />
                  <span>Row Level Security включен автоматически</span>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </CardContent>
      </Card>
    </motion.div>
  );
}

// Helper functions
function getTableFriendlyName(tableName: string): string {
  const names: Record<string, string> = {
    'game_scores': 'Результаты игры',
    'scores': 'Очки',
    'achievements': 'Достижения',
    'profiles': 'Профили',
    'user_progress': 'Прогресс',
    'leaderboard': 'Рейтинг',
    'messages': 'Сообщения',
    'workouts': 'Тренировки',
    'products': 'Товары',
    'orders': 'Заказы',
    'users': 'Пользователи',
    'bookings': 'Бронирования',
    'reviews': 'Отзывы',
    'favorites': 'Избранное',
    'notifications': 'Уведомления',
  };
  return names[tableName] || tableName;
}

function getTablePurpose(tableName: string): string {
  const purposes: Record<string, string> = {
    'game_scores': 'результатов и рейтинга',
    'scores': 'игровых очков',
    'achievements': 'наград и достижений',
    'profiles': 'профилей пользователей',
    'user_progress': 'прогресса и сохранений',
    'leaderboard': 'таблицы лидеров',
    'messages': 'сообщений',
    'workouts': 'тренировок',
    'products': 'товаров',
    'orders': 'заказов',
    'bookings': 'бронирований',
    'reviews': 'отзывов',
  };
  return purposes[tableName] || 'данных';
}

export default AutoMigrationCard;
