import { useState, useMemo } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { 
  Lightbulb,
  Link2,
  FileText,
  FileEdit,
  CheckCircle2,
  XCircle,
  Loader2,
  ChevronDown,
  ChevronUp,
  Database,
  AlertCircle,
  ShieldCheck,
  ListTodo
} from 'lucide-react';
import { Collapsible, CollapsibleContent, CollapsibleTrigger } from '@/components/ui/collapsible';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { StreamingTextByWord } from './StreamingText';
import { ValidationBadge } from './ValidationBadge';
import { AutoFixIndicator } from './AutoFixIndicator';
import { AutoMigrationCard } from '@/components/builder/AutoMigrationCard';
import type { RunSummary } from './RunSummaryCard';
import type { ChatTimelineEvent, ChatVersionDiff } from '@/lib/chat-ui-event-contract';
import { humanizeToolName } from '@/lib/chat-ui-event-contract';
import type { AgentStep, ValidationState, PendingMigration } from '@/hooks/useUnifiedOrchestrator';
import { RunSummaryPopover } from './RunSummaryPopover';

interface AgentStreamBlocksProps {
  steps: AgentStep[];
  textContent?: string;
  isStreaming?: boolean;
  thinkingDuration?: number;
  /** If true, text appears with typing animation */
  enableTextStreaming?: boolean;
  /** Validation results from orchestrator */
  validation?: ValidationState | null;
  /** Auto-fix state */
  autoFix?: {
    isAutoFixing: boolean;
    attempt: number;
    maxAttempts: number;
    currentScore?: number;
  };
  /** Database migration pending approval */
  pendingMigration?: {
    sql: string;
    description?: string;
    tables?: string[];
    status?: 'pending' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed';
    result?: {
      success: boolean;
      message?: string;
      results?: Array<{ statement: string; success: boolean; error?: string }>;
    };
    /** Auto-generated migration fields */
    autoGenerated?: boolean;
    requiresAuth?: boolean;
    features?: string[];
  };
  runSummary?: RunSummary;
  timelineEvents?: ChatTimelineEvent[];
  versionDiff?: ChatVersionDiff | null;
  onMigrationApprove?: () => void;
  onMigrationReject?: () => void;
}

function stripRunSummarySection(value: string): string {
  const marker = '\n\nИтог анализа:';
  const idx = value.indexOf(marker);
  if (idx === -1) return value;
  return value.slice(0, idx).trim();
}

function stripSystemCompletionHeaders(value: string): string {
  const lines = String(value || "").split('\n');
  while (lines.length > 0) {
    const normalized = lines[0]
      .replace(/[✅✔]/g, '')
      .replace(/\s+/g, ' ')
      .trim()
      .toLowerCase();
    if (
      normalized === 'generation complete' ||
      normalized === 'генерация завершена' ||
      normalized === 'generation finished'
    ) {
      lines.shift();
      continue;
    }
    break;
  }
  return lines.join('\n').trim();
}

function compactRepeatedText(value: string): string {
  const lines = String(value || "").split('\n');
  const compact: string[] = [];
  let prev = '';
  for (const line of lines) {
    const normalized = line.replace(/\s+/g, ' ').trim();
    if (!normalized && prev === '') {
      continue;
    }
    if (normalized && normalized === prev) {
      continue;
    }
    compact.push(line);
    prev = normalized;
  }
  return compact.join('\n').trim();
}

function shouldSuppressRichFailureText(value: string, status?: RunSummary['status']): boolean {
  if (status !== 'failed' && status !== 'cancelled') return false;
  const normalized = String(value || '').replace(/\s+/g, ' ').trim().toLowerCase();
  if (!normalized) return false;
  return (
    normalized.includes('ошибка генерации') ||
    normalized.includes('не удалось завершить генерацию') ||
    normalized.includes('попробуйте переформулировать запрос') ||
    normalized.includes('повторите попытку')
  );
}

function normalizeFileAction(action: string | undefined): 'created' | 'modified' | 'deleted' {
  const normalized = String(action || '').trim().toLowerCase();
  if (
    normalized === 'created' ||
    normalized === 'create' ||
    normalized.includes('create')
  ) {
    return 'created';
  }
  if (
    normalized === 'deleted' ||
    normalized === 'delete' ||
    normalized === 'removed' ||
    normalized.includes('delete') ||
    normalized.includes('remove')
  ) {
    return 'deleted';
  }
  return 'modified';
}

function humanizeAgentHeading(value?: string): string {
  const normalized = String(value || '').trim().toLowerCase();
  if (!normalized) return 'AI-агент сборки';
  if (/adk sequentialagent|sequentialagent|agent/i.test(normalized)) return 'AI-агент сборки';
  if (/critic review|review/i.test(normalized)) return 'Проверка результата';
  if (/generate operations|execute|execution/i.test(normalized)) return 'Сборка экранов и компонентов';
  if (/^plan$/i.test(normalized)) return 'План структуры';
  return String(value || '').trim();
}

function humanizePlanTask(value: string): string {
  const normalized = String(value || '').trim().toLowerCase();
  if (!normalized) return '';
  if (/critic review|review/.test(normalized)) return 'Проверить качество, кликабельность и целостность';
  if (/generate operations|implementation|execute/.test(normalized)) return 'Собрать экраны, секции и основные действия';
  if (/^plan$|structure plan|planning/.test(normalized)) return 'Сформировать понятную структуру проекта';
  if (/clarif|question/.test(normalized)) return 'Уточнить ключевые требования перед сборкой';
  return String(value || '').trim().replace(/\bplan\b/i, 'План').replace(/\bcritic review\b/i, 'Проверка результата');
}

function humanizeRunStatus(status?: RunSummary['status'], isStreaming?: boolean): string {
  if (isStreaming) return 'Генерирую проект…';
  switch (status) {
    case 'success':
      return 'Проект собран';
    case 'failed':
      return 'Сборка остановилась с ошибкой';
    case 'cancelled':
      return 'Генерация остановлена';
    default:
      return 'История запуска';
  }
}

function humanizeRunSubstatus(status?: RunSummary['status']): string {
  switch (status) {
    case 'success':
      return 'Карточка сохранена в истории. Можно продолжать доработку с этого состояния.';
    case 'failed':
      return 'Часть шагов сохранилась. Можно уточнить задачу и перезапустить сборку.';
    case 'cancelled':
      return 'Шаги и изменения сохранены. Можно продолжить с новой команды.';
    default:
      return 'Показываю актуальный прогресс по текущему запуску.';
  }
}

function formatLiveStepLabel(step: AgentStep | null): string {
  if (!step) return 'Генерирую проект…';

  if (step.type === 'plan') return 'Собираю план структуры…';
  if (step.type === 'thinking') return 'Анализирую запрос…';
  if (step.type === 'validation') return 'Проверяю качество и целостность…';
  if (step.type === 'tool_result' && step.success === false) return 'Исправляю проблему и обновляю проект…';
  if (step.type === 'tool_call') {
    const tool = humanizeToolName(step.name || 'Действие');
    return `${tool}…`;
  }
  if (step.type === 'complete') return 'Финализирую результат…';
  if (step.content && step.content.trim()) return humanizePlanTask(step.content.trim());
  return 'Генерирую проект…';
}

function prettifyTimelineLabel(event: ChatTimelineEvent): string {
  const rawLabel = String(event.label || "").trim();
  const normalizedLabel = rawLabel
    .replace(/^phase\s*[•:]\s*/i, "")
    .replace(/^tool_call\s*[•:]\s*/i, "")
    .replace(/^tool_result\s*[•:]\s*/i, "")
    .replace(/^complete\s*[•:]\s*/i, "")
    .replace(/^validation\s*[•:]\s*/i, "")
    .replace(/^plan\s*[•:]\s*/i, "")
    .trim();

  if (event.eventType === "tool_call") {
    return `Инструмент: ${humanizeToolName(normalizedLabel || rawLabel || "Действие")}`;
  }
  if (event.eventType === "tool_result") {
    return `Результат: ${humanizeToolName(normalizedLabel || rawLabel || "Действие")}`;
  }
  if (event.eventType === "phase") {
    return `Этап: ${humanizePlanTask(normalizedLabel || "выполнение")}`;
  }
  if (event.eventType === "validation") {
    return `Проверка: ${humanizePlanTask(normalizedLabel || "качество результата")}`;
  }
  if (event.eventType === "plan") {
    return `План: ${humanizePlanTask(normalizedLabel || "структура подготовлена")}`;
  }
  if (event.eventType === "thinking") {
    return `Анализ: ${humanizePlanTask(normalizedLabel || "в процессе")}`;
  }
  if (event.eventType === "complete") {
    return `Финализация: ${humanizePlanTask(normalizedLabel || "завершено")}`;
  }
  return humanizePlanTask(rawLabel || event.eventType);
}

// Thought for Xs badge
function ThoughtBadge({ duration }: { duration: number }) {
  const seconds = Math.round(duration / 1000);
  return (
    <div className="flex items-center gap-2 text-muted-foreground py-1">
      <Lightbulb className="w-4 h-4" />
      <span className="text-sm">Анализ занял {seconds}с</span>
    </div>
  );
}

// Tools used badge with expandable list
function ToolsUsedBadge({ 
  count, 
  tools,
  allSteps 
}: { 
  count: number; 
  tools: AgentStep[];
  allSteps: AgentStep[];
}) {
  const [isOpen, setIsOpen] = useState(false);
  
  // Filter out empty tools
  const validTools = tools.filter(t => t.name && t.name.trim() !== '');
  const actualCount = validTools.length;
  
  // Don't render if no valid tools
  if (actualCount === 0) return null;
  
  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <CollapsibleTrigger asChild>
        <button className="flex items-center gap-3 py-1.5 group w-full">
          <div className="flex items-center gap-2 text-muted-foreground">
            <Link2 className="w-4 h-4" />
            <span className="text-sm">Инструменты: {actualCount}</span>
          </div>
          <div className="flex-1" />
          <span className="text-sm text-muted-foreground border border-border rounded-md px-2.5 py-0.5 hover:bg-muted transition-colors">
            {isOpen ? 'Скрыть' : 'Показать'}
          </span>
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <motion.div 
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          exit={{ opacity: 0, height: 0 }}
          className="pl-6 space-y-1 py-2"
        >
          {validTools.map((step) => {
            const resultStep = allSteps.find(
              s => s.type === 'tool_result' && s.id === step.id
            );
            const data = step.data as { path?: string } | undefined;
            
            return (
              <div 
                key={step.id} 
                className="flex items-center gap-2 text-xs text-muted-foreground"
              >
                {resultStep?.success === false ? (
                  <XCircle className="w-3.5 h-3.5 text-red-500 flex-shrink-0" />
                ) : resultStep?.success === true ? (
                  <CheckCircle2 className="w-3.5 h-3.5 text-green-500 flex-shrink-0" />
                ) : (
                  <Loader2 className="w-3.5 h-3.5 animate-spin flex-shrink-0" />
                )}
                <span className="font-medium text-foreground">{humanizeToolName(step.name) || 'Действие'}</span>
                {data?.path && (
                  <code className="px-1.5 py-0.5 bg-muted rounded text-[10px] font-mono">
                    {data.path.split('/').pop()}
                  </code>
                )}
              </div>
            );
          })}
        </motion.div>
      </CollapsibleContent>
    </Collapsible>
  );
}

// Read file badge
function ReadBadge({ filename }: { filename: string }) {
  return (
    <motion.div 
      initial={{ opacity: 0, x: -10 }}
      animate={{ opacity: 1, x: 0 }}
      className="flex items-center gap-2 py-1"
    >
      <FileText className="w-4 h-4 text-muted-foreground" />
      <span className="text-sm text-muted-foreground">Прочитан файл</span>
      <code className="px-2 py-0.5 bg-muted rounded text-xs font-mono text-foreground">
        {filename}
      </code>
    </motion.div>
  );
}

// Read database logs badge with animation
function ReadDatabaseLogsBadge({ logType }: { logType: 'postgres' | 'auth' | 'edge' | 'analytics' }) {
  const labels: Record<string, string> = {
    postgres: 'логи базы данных',
    auth: 'логи авторизации',
    edge: 'логи edge-функций',
    analytics: 'аналитика',
  };
  
  return (
    <motion.div 
      initial={{ opacity: 0, x: -10, scale: 0.95 }}
      animate={{ opacity: 1, x: 0, scale: 1 }}
      transition={{ type: 'spring', stiffness: 300, damping: 20 }}
      className="flex items-center gap-2 py-1.5"
    >
      <div className="relative">
        <Database className="w-4 h-4 text-blue-500" />
        <motion.div
          initial={{ scale: 0 }}
          animate={{ scale: [0, 1.2, 1] }}
          transition={{ delay: 0.2, duration: 0.3 }}
          className="absolute -top-0.5 -right-0.5 w-2 h-2 bg-blue-500 rounded-full"
        />
      </div>
      <span className="text-sm text-muted-foreground">Читаю</span>
      <code className="px-2 py-0.5 bg-blue-500/10 border border-blue-500/20 rounded text-xs font-mono text-blue-600 dark:text-blue-400">
        {labels[logType] || 'данные'}
      </code>
    </motion.div>
  );
}

function PlanCard({
  title,
  tasks,
}: {
  title: string;
  tasks: string[];
}) {
  if (!tasks.length) return null;
  return (
    <div className="rounded-lg border border-border/70 bg-background/60 p-3">
      <div className="mb-2 flex items-center gap-2 text-sm font-medium text-foreground">
        <ListTodo className="h-4 w-4 text-primary" />
        <span>{humanizeAgentHeading(title || 'План работы')}</span>
      </div>
      <div className="space-y-1.5">
        {tasks.map((task, index) => (
          <div key={`${task}-${index}`} className="flex items-start gap-2 text-sm text-muted-foreground">
            <span className="mt-[3px] inline-block h-1.5 w-1.5 rounded-full bg-primary/70" />
            <span>{humanizePlanTask(task)}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function LiveGenerationCard({
  statusText,
  currentAction,
  fileActions,
  status,
  timelinePreview,
}: {
  statusText: string;
  currentAction: string;
  fileActions: Array<{ path: string; action: 'created' | 'modified' | 'deleted' }>;
  status: 'streaming' | 'success' | 'failed' | 'cancelled';
  timelinePreview: string[];
}) {
  const visibleFiles = fileActions.slice(0, 4);
  const isStreaming = status === 'streaming';
  const statusTone =
    status === 'success'
      ? 'border-emerald-500/20 bg-emerald-500/5'
      : status === 'failed'
        ? 'border-red-500/20 bg-red-500/5'
        : status === 'cancelled'
          ? 'border-amber-500/20 bg-amber-500/5'
          : 'border-border/60 bg-muted/20';
  const railTone =
    status === 'success'
      ? 'bg-emerald-500'
      : status === 'failed'
        ? 'bg-red-500'
        : status === 'cancelled'
          ? 'bg-amber-500'
          : 'bg-primary';

  return (
    <motion.div
      initial={{ opacity: 0, y: 6 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn("relative overflow-hidden rounded-xl border px-3 py-3", statusTone)}
    >
      {isStreaming ? (
        <motion.div
          aria-hidden
          className="pointer-events-none absolute inset-0 bg-[linear-gradient(110deg,transparent_0%,rgba(255,255,255,0.32)_45%,transparent_100%)] dark:bg-[linear-gradient(110deg,transparent_0%,rgba(255,255,255,0.08)_45%,transparent_100%)]"
          animate={{ x: ['-140%', '140%'] }}
          transition={{ duration: 2.8, repeat: Infinity, ease: 'easeInOut' }}
        />
      ) : null}

      <div className="relative space-y-3">
        <div className="flex gap-1.5">
          {[0, 1, 2].map((index) => (
            <motion.span
              key={index}
              className={cn("h-1 rounded-full", railTone)}
              initial={{ opacity: 0.35, scaleX: 0.85 }}
              animate={
                isStreaming
                  ? { opacity: [0.35, 1, 0.35], scaleX: [0.85, 1, 0.85] }
                  : { opacity: 0.9, scaleX: 1 }
              }
              transition={{
                duration: 1.4,
                repeat: isStreaming ? Infinity : 0,
                delay: index * 0.12,
                ease: 'easeInOut',
              }}
              style={{ width: `${28 + index * 12}px` }}
            />
          ))}
        </div>

        <div className="flex items-center gap-2">
          <motion.span
            className={cn("inline-flex h-2.5 w-2.5 rounded-full", railTone)}
            animate={
              isStreaming
                ? { scale: [1, 1.35, 1], opacity: [0.7, 1, 0.7] }
                : { scale: [1, 1.08, 1], opacity: [0.88, 1, 0.88] }
            }
            transition={{ duration: isStreaming ? 1.6 : 2.2, repeat: Infinity, ease: 'easeInOut' }}
          />
          <div className="min-w-0">
            <div className="text-sm font-medium text-foreground">{statusText}</div>
            <div className="text-xs text-muted-foreground">{humanizeRunSubstatus(status === 'streaming' ? undefined : status)}</div>
          </div>
        </div>

        <AnimatePresence mode="wait" initial={false}>
          <motion.div
            key={currentAction}
            initial={{ opacity: 0, y: 4 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -4 }}
            transition={{ duration: 0.18 }}
            className="text-sm text-muted-foreground"
          >
            {currentAction}
          </motion.div>
        </AnimatePresence>

        {timelinePreview.length > 0 && (
          <div className="grid gap-1.5">
            <AnimatePresence initial={false}>
              {timelinePreview.slice(0, 3).map((label, index) => (
                <motion.div
                  key={`${label}-${index}`}
                  initial={{ opacity: 0, x: -6 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 6 }}
                  transition={{ duration: 0.22, delay: index * 0.04 }}
                  className="flex items-center gap-2 text-xs text-muted-foreground"
                >
                  <motion.span
                    className={cn("h-1.5 w-1.5 rounded-full", railTone)}
                    animate={
                      index === 0
                        ? { scale: [1, 1.4, 1], opacity: [0.6, 1, 0.6] }
                        : undefined
                    }
                    transition={{ duration: 1.5, repeat: Infinity, ease: 'easeInOut' }}
                  />
                  <span>{label}</span>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}

        {visibleFiles.length > 0 && (
          <div className="flex flex-wrap gap-1.5">
            <AnimatePresence initial={false}>
              {visibleFiles.map((file) => (
                <motion.div
                  key={`${file.action}:${file.path}`}
                  layout
                  initial={{ opacity: 0, scale: 0.92, y: 4 }}
                  animate={{ opacity: 1, scale: 1, y: 0 }}
                  exit={{ opacity: 0, scale: 0.92 }}
                  className={cn(
                    "inline-flex items-center gap-1 rounded-full border px-2 py-1 text-[11px] font-medium",
                    file.action === 'created' && "border-green-500/20 bg-green-500/10 text-green-700 dark:text-green-300",
                    file.action === 'modified' && "border-blue-500/20 bg-blue-500/10 text-blue-700 dark:text-blue-300",
                    file.action === 'deleted' && "border-red-500/20 bg-red-500/10 text-red-700 dark:text-red-300"
                  )}
                >
                  <span className="font-semibold">
                    {file.action === 'created' ? '+' : file.action === 'deleted' ? '−' : '~'}
                  </span>
                  <span className="max-w-[180px] truncate">{file.path.split('/').pop() || file.path}</span>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        )}
      </div>
    </motion.div>
  );
}

// Editing file badge
function EditingBadge({ filename }: { filename: string }) {
  return (
    <div className="flex items-center gap-2 py-1">
      <FileEdit className="w-4 h-4 text-muted-foreground" />
      <span className="text-sm text-muted-foreground">Обновляю файл</span>
      <code className="px-2 py-0.5 bg-muted rounded text-xs font-mono text-foreground">
        {filename}
      </code>
    </div>
  );
}

// Edits made badge with expandable list  
function EditsMadeBadge({ 
  count,
  edits 
}: { 
  count: number;
  edits: Array<{ path: string; action: string }>;
}) {
  const [isOpen, setIsOpen] = useState(false);
  
  // Filter out empty or invalid edits
  const validEdits = edits.filter(e => e.path && e.path.trim() !== '');
  const actualCount = validEdits.length;
  
  // Don't render if no valid edits
  if (actualCount === 0) return null;
  
  return (
    <Collapsible open={isOpen} onOpenChange={setIsOpen}>
      <CollapsibleTrigger asChild>
        <button className="flex items-center gap-3 py-1.5 group w-full">
          <div className="flex items-center gap-2 text-muted-foreground">
            <FileEdit className="w-4 h-4" />
            <span className="text-sm">Изменения: {actualCount}</span>
          </div>
          <div className="flex-1" />
          <span className="text-sm text-muted-foreground border border-border rounded-md px-2.5 py-0.5 hover:bg-muted transition-colors">
            {isOpen ? 'Скрыть' : 'Показать'}
          </span>
        </button>
      </CollapsibleTrigger>
      <CollapsibleContent>
        <motion.div 
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: 'auto' }}
          exit={{ opacity: 0, height: 0 }}
          className="pl-6 space-y-1 py-2"
        >
          {validEdits.map((edit, i) => (
            <div 
              key={`${edit.path}-${i}`} 
              className="flex items-center gap-2 text-xs"
            >
              {edit.action === 'created' ? (
                <span className="text-green-500 font-bold">+</span>
              ) : edit.action === 'deleted' ? (
                <span className="text-red-500 font-bold">−</span>
              ) : (
                <span className="text-yellow-500 font-bold">~</span>
              )}
              <span className={cn(
                'font-medium',
                edit.action === 'created' && 'text-green-600 dark:text-green-400',
                edit.action === 'deleted' && 'text-red-600 dark:text-red-400',
                edit.action === 'modified' && 'text-yellow-600 dark:text-yellow-400'
              )}>
                {edit.action === 'created' ? 'Создан' : 
                 edit.action === 'deleted' ? 'Удалён' : 'Обновлён'}
              </span>
              <code className="px-1.5 py-0.5 bg-muted rounded text-[10px] font-mono">
                {edit.path.split('/').pop()}
              </code>
            </div>
          ))}
        </motion.div>
      </CollapsibleContent>
    </Collapsible>
  );
}

// Database modification badge with approval UI and result animation
function DatabaseModifiedBadge({ 
  migration,
  status,
  result,
  onApprove,
  onReject
}: { 
  migration: { 
    sql: string; 
    description?: string;
    tables?: string[];
  };
  status?: 'pending' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed';
  result?: {
    success: boolean;
    message?: string;
    results?: Array<{ statement: string; success: boolean; error?: string }>;
  };
  onApprove?: () => void;
  onReject?: () => void;
}) {
  const [isOpen, setIsOpen] = useState(true);
  
  const statusConfig = {
    pending: { bg: 'amber', icon: AlertCircle, label: 'Нужно подтверждение', animate: true },
    approved: { bg: 'blue', icon: Loader2, label: 'Подтверждено', animate: false },
    executing: { bg: 'blue', icon: Loader2, label: 'Выполняю...', animate: true },
    completed: { bg: 'green', icon: CheckCircle2, label: 'Готово', animate: false },
    failed: { bg: 'red', icon: XCircle, label: 'Ошибка', animate: false },
    rejected: { bg: 'red', icon: XCircle, label: 'Отклонено', animate: false },
  };
  
  const config = statusConfig[status || 'pending'];
  const StatusIcon = config.icon;
  
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      className={cn(
        "rounded-lg border overflow-hidden transition-colors",
        status === 'completed' && "border-green-500/30 bg-green-500/5",
        status === 'failed' && "border-red-500/30 bg-red-500/5",
        status === 'rejected' && "border-red-500/30 bg-red-500/5",
        status === 'executing' && "border-blue-500/30 bg-blue-500/5",
        (!status || status === 'pending') && "border-amber-500/30 bg-amber-500/5"
      )}
    >
      <Collapsible open={isOpen} onOpenChange={setIsOpen}>
        <CollapsibleTrigger asChild>
          <button className="flex items-center gap-3 py-2.5 px-3 group w-full">
            <div className="flex items-center gap-2">
              <Database className={cn(
                "w-4 h-4",
                status === 'completed' && "text-green-500",
                status === 'failed' && "text-red-500",
                status === 'rejected' && "text-red-500",
                status === 'executing' && "text-blue-500",
                (!status || status === 'pending') && "text-amber-500"
              )} />
              <span className="text-sm font-medium">Изменения в базе данных</span>
              
              <motion.span 
                initial={{ opacity: 0, scale: 0.8 }}
                animate={{ opacity: 1, scale: 1 }}
                key={status}
                className={cn(
                  "px-2 py-0.5 rounded-full text-xs flex items-center gap-1",
                  status === 'completed' && "bg-green-500/20 text-green-600",
                  status === 'failed' && "bg-red-500/20 text-red-500",
                  status === 'rejected' && "bg-red-500/20 text-red-500",
                  status === 'executing' && "bg-blue-500/20 text-blue-600",
                  (!status || status === 'pending') && "bg-amber-500/20 text-amber-600"
                )}
              >
                <StatusIcon className={cn(
                  "w-3 h-3",
                  config.animate && status === 'executing' && "animate-spin"
                )} />
                {config.label}
              </motion.span>
            </div>
            <div className="flex-1" />
            <ChevronDown className={cn(
              "w-4 h-4 text-muted-foreground transition-transform",
              isOpen && "rotate-180"
            )} />
          </button>
        </CollapsibleTrigger>
        <CollapsibleContent>
          <div className="px-3 pb-3 space-y-3">
            {migration.description && (
              <p className="text-xs text-muted-foreground">{migration.description}</p>
            )}
            
            {migration.tables && migration.tables.length > 0 && (
              <div className="flex flex-wrap gap-1">
                {migration.tables.map((table) => (
                  <code key={table} className="px-1.5 py-0.5 bg-muted rounded text-[10px] font-mono">
                    {table}
                  </code>
                ))}
              </div>
            )}
            
            <pre className="text-[10px] font-mono bg-muted/50 p-2 rounded overflow-x-auto max-h-32 text-muted-foreground">
              {migration.sql.slice(0, 500)}
              {migration.sql.length > 500 && '...'}
            </pre>
            
            {/* Result feedback */}
            <AnimatePresence>
              {(status === 'completed' || status === 'failed') && result && (
                <motion.div
                  initial={{ opacity: 0, height: 0 }}
                  animate={{ opacity: 1, height: 'auto' }}
                  exit={{ opacity: 0, height: 0 }}
                  className={cn(
                    "rounded-md p-2 text-xs",
                    status === 'completed' && "bg-green-500/10 border border-green-500/20",
                    status === 'failed' && "bg-red-500/10 border border-red-500/20"
                  )}
                >
                  <div className="flex items-center gap-2 mb-1">
                    {status === 'completed' ? (
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: [0, 1.2, 1] }}
                        transition={{ type: 'spring', stiffness: 300 }}
                      >
                        <CheckCircle2 className="w-4 h-4 text-green-500" />
                      </motion.div>
                    ) : (
                      <motion.div
                        initial={{ scale: 0 }}
                        animate={{ scale: [0, 1.2, 1] }}
                        transition={{ type: 'spring', stiffness: 300 }}
                      >
                        <XCircle className="w-4 h-4 text-red-500" />
                      </motion.div>
                    )}
                    <span className={cn(
                      "font-medium",
                      status === 'completed' ? "text-green-600" : "text-red-500"
                    )}>
                      {result.message || (status === 'completed' ? 'Изменения применены' : 'Не удалось применить изменения')}
                    </span>
                  </div>
                  
                  {result.results && result.results.some(r => !r.success) && (
                    <div className="mt-2 space-y-1">
                      {result.results.filter(r => !r.success).map((r, i) => (
                        <div key={i} className="text-red-400 text-[10px] font-mono">
                          {r.error}
                        </div>
                      ))}
                    </div>
                  )}
                </motion.div>
              )}
            </AnimatePresence>
            
            {/* Executing indicator */}
            {status === 'executing' && (
              <motion.div
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                className="flex items-center gap-2 text-xs text-blue-600"
              >
                <Loader2 className="w-3 h-3 animate-spin" />
                <span>Выполняю изменения в базе…</span>
              </motion.div>
            )}
            
            {/* Approval buttons - only show when pending */}
            {(!status || status === 'pending') && onApprove && onReject && (
              <div className="flex gap-2">
                <Button 
                  size="sm" 
                  variant="default"
                  onClick={onApprove}
                  className="flex-1 h-7 text-xs bg-green-600 hover:bg-green-700"
                >
                  <CheckCircle2 className="w-3 h-3 mr-1" />
                  Подтвердить
                </Button>
                <Button 
                  size="sm" 
                  variant="outline"
                  onClick={onReject}
                  className="flex-1 h-7 text-xs hover:bg-red-500/10 hover:text-red-500 hover:border-red-500/50"
                >
                  <XCircle className="w-3 h-3 mr-1" />
                  Отклонить
                </Button>
              </div>
            )}
          </div>
        </CollapsibleContent>
      </Collapsible>
    </motion.div>
  );
}

export function AgentStreamBlocks({
  steps, 
  textContent,
  isStreaming,
  thinkingDuration,
  enableTextStreaming = false,
  validation,
  autoFix,
  pendingMigration,
  runSummary,
  timelineEvents,
  versionDiff,
  onMigrationApprove,
  onMigrationReject
}: AgentStreamBlocksProps) {
  const [showDetails, setShowDetails] = useState(false);
  const visibleTimelineEvents = useMemo(() => {
    if (!timelineEvents || timelineEvents.length === 0) return [];
    const compact = timelineEvents.filter(
      (event) => event.eventType !== 'text' && event.eventType !== 'other'
    );
    const deduped: ChatTimelineEvent[] = [];
    for (const event of compact) {
      const prev = deduped[deduped.length - 1];
      const key = `${event.eventType}:${event.label}:${event.path || ''}:${event.status}`;
      const prevKey = prev
        ? `${prev.eventType}:${prev.label}:${prev.path || ''}:${prev.status}`
        : '';
      if (key === prevKey) continue;
      deduped.push(event);
    }
    return deduped.slice(-8);
  }, [timelineEvents]);

  // Group steps into blocks for display
  const blocks = useMemo(() => {
    const result: Array<{
      type: 'thought' | 'plan' | 'text' | 'tools' | 'read' | 'edit' | 'edits' | 'database' | 'db_logs' | 'validation';
      content?: string;
      duration?: number;
      count?: number;
      filename?: string;
      logType?: 'postgres' | 'auth' | 'edge' | 'analytics';
      tools?: AgentStep[];
      edits?: Array<{ path: string; action: string }>;
      validationData?: ValidationState;
      plan?: {
        title: string;
        tasks: string[];
      };
      migration?: { 
        sql: string; 
        description?: string; 
        tables?: string[];
        status?: 'pending' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed';
        result?: {
          success: boolean;
          message?: string;
          results?: Array<{ statement: string; success: boolean; error?: string }>;
        };
        /** Auto-generated migration fields for AutoMigrationCard */
        autoGenerated?: boolean;
        requiresAuth?: boolean;
        features?: string[];
      };
    }> = [];
    
    // Add thinking duration if present
    if (thinkingDuration && thinkingDuration > 0) {
      result.push({ type: 'thought', duration: thinkingDuration });
    }
    
    // Group consecutive text content
    const textParts: string[] = [];
    const toolCalls: AgentStep[] = [];
    const fileEdits: Array<{ path: string; action: string }> = [];
    const filesRead: string[] = [];
    const dbLogsRead: Array<'postgres' | 'auth' | 'edge' | 'analytics'> = [];
    let planCard: { title: string; tasks: string[] } | null = null;
    let dbMigration: { sql: string; description?: string; tables?: string[] } | null = null;
    
    steps.forEach((step) => {
      if (step.type === 'plan') {
        const data = step.data as { tasks?: string[] } | undefined;
        const tasks = Array.isArray(data?.tasks)
          ? data.tasks.map((entry) => String(entry || '').trim()).filter(Boolean).slice(0, 5)
          : [];
        if (tasks.length > 0) {
          planCard = {
            title: step.content || 'План работы',
            tasks,
          };
        }
      }

      // Collect tool calls
      if (step.type === 'tool_call') {
        toolCalls.push(step);
        
        // Extract path from data OR args (for DB-loaded steps)
        const data = step.data as { path?: string } | undefined;
        const args = step.args as { path?: string } | undefined;
        const path = data?.path || args?.path;
        
        // Check if it's a read operation
        if (step.name?.toLowerCase().includes('read')) {
          if (path) {
            filesRead.push(path);
          }
        }
        
        // Check if it's a file create/edit operation - add to edits
        if (step.name?.toLowerCase().includes('create') || 
            step.name?.toLowerCase().includes('edit') || 
            step.name?.toLowerCase().includes('write')) {
          if (path) {
            const action = step.name?.toLowerCase().includes('create') ? 'created' : 'modified';
            fileEdits.push({ path, action });
          }
        }
        
        // Check for database log reading
        if (step.name?.toLowerCase().includes('analytics') || step.name?.toLowerCase().includes('logs')) {
          const stepName = step.name?.toLowerCase() || '';
          if (stepName.includes('postgres') || stepName.includes('database')) {
            dbLogsRead.push('postgres');
          } else if (stepName.includes('auth')) {
            dbLogsRead.push('auth');
          } else if (stepName.includes('edge') || stepName.includes('function')) {
            dbLogsRead.push('edge');
          } else if (stepName.includes('analytics')) {
            dbLogsRead.push('analytics');
          }
        }
        
        // Check for database migration
        if (step.name?.toLowerCase().includes('migration') || step.name?.toLowerCase().includes('database')) {
          const data = step.data as { sql?: string; query?: string; description?: string; tables?: string[] } | undefined;
          const args = step.args as { sql?: string; query?: string; description?: string; tables?: string[] } | undefined;
          const sql = data?.sql || data?.query || args?.sql || args?.query;
          if (sql) {
            dbMigration = {
              sql,
              description: data?.description || args?.description,
              tables: data?.tables || args?.tables
            };
          }
        }
      }
      
      // Collect file edits from tool results
      if (step.type === 'tool_result') {
        const data = step.data as { path?: string; action?: string } | undefined;
        const args = step.args as { path?: string; action?: string } | undefined;
        const path = data?.path || args?.path;
        const action = data?.action || args?.action;
        
        if (path && action) {
          // Don't duplicate if already added from tool_call
          if (!fileEdits.some(e => e.path === path)) {
            fileEdits.push({ path, action });
          }
        }
      }
      
      // Show only explicit text stream as main chat content.
      // Technical step payloads stay in Details/Timeline.
      if (step.content && step.type === 'text') {
        textParts.push(step.content);
      }
      
    });
    
    // Add text content block
    if (planCard) {
      result.push({ type: 'plan', plan: planCard });
    }

    if (textContent || textParts.length > 0) {
      const rawContent = textContent || textParts.join('\n');
      const content = compactRepeatedText(stripSystemCompletionHeaders(
        runSummary ? stripRunSummarySection(rawContent) : rawContent
      ));
      if (content.trim() && !shouldSuppressRichFailureText(content, runSummary?.status)) {
        result.push({ type: 'text', content });
      }
    }
    
    // Add tools used block - only if we have valid tools with names
    const validTools = toolCalls.filter(t => t.name && t.name.trim() !== '');
    if (validTools.length > 0) {
      result.push({ type: 'tools', count: validTools.length, tools: validTools });
    }
    
    // Add read files blocks - only if we have actual filenames
    const validReads = filesRead.filter(f => f && f.trim() !== '');
    validReads.forEach(filename => {
      result.push({ type: 'read', filename: filename.split('/').pop() || filename });
    });
    
    // Add edits made block - only if we have valid edits with paths
    const diffEdits = (versionDiff?.filesChanged || []).filter((entry) => entry.path && entry.path.trim() !== '');
    const validEdits = (diffEdits.length > 0 ? diffEdits : fileEdits).filter(e => e.path && e.path.trim() !== '');
    if (validEdits.length > 0) {
      result.push({ type: 'edits', count: validEdits.length, edits: validEdits });
    }
    
    // Add database logs read blocks
    dbLogsRead.forEach(logType => {
      result.push({ type: 'db_logs', logType });
    });
    
    // Add database migration block (from steps or prop)
    if (dbMigration) {
      result.push({ type: 'database', migration: { ...dbMigration, status: 'pending' } });
    } else if (pendingMigration) {
      result.push({ 
        type: 'database', 
        migration: {
          sql: pendingMigration.sql,
          description: pendingMigration.description,
          tables: pendingMigration.tables,
          status: pendingMigration.status,
          result: pendingMigration.result,
          // 🆕 Pass auto-generated migration fields for AutoMigrationCard
          autoGenerated: pendingMigration.autoGenerated,
          requiresAuth: pendingMigration.requiresAuth,
          features: pendingMigration.features,
        }
      });
    }
    
    // Add validation block if available
    if (validation && validation.score !== undefined) {
      result.push({ type: 'validation', validationData: validation });
    }
    
    return result;
  }, [steps, textContent, thinkingDuration, pendingMigration, validation, runSummary, versionDiff]);

  const liveStatusText = useMemo(() => {
    if (!isStreaming) return '';
    if (pendingMigration?.status === 'executing') return 'Применяю изменения и собираю обновление…';
    const hasWriteStep = steps.some((step) => {
      const name = String(step.name || '').toLowerCase();
      return step.type === 'tool_call' && /create|edit|write|modify|patch/.test(name);
    });
    const hasReadStep = steps.some((step) => {
      const name = String(step.name || '').toLowerCase();
      return step.type === 'tool_call' && /read|analy|inspect|search|list/.test(name);
    });
    if (hasWriteStep) return 'Собираю структуру проекта и компоненты…';
    if (hasReadStep) return 'Анализирую запрос и подготавливаю проект…';
    return 'Генерирую проект…';
  }, [isStreaming, pendingMigration?.status, steps]);

  const liveCurrentStep = useMemo(() => {
    for (let index = steps.length - 1; index >= 0; index -= 1) {
      const step = steps[index];
      if (!step) continue;
      if (step.type === 'text') continue;
      if (step.type === 'tool_result' && step.success === true) continue;
      return step;
    }
    return null;
  }, [steps]);

  const liveFileActions = useMemo(() => {
    const collected: Array<{ path: string; action: 'created' | 'modified' | 'deleted' }> = [];

    for (const step of steps) {
      const data = step.data as { path?: string; action?: string } | undefined;
      const args = step.args as { path?: string; action?: string } | undefined;
      const path = String(data?.path || args?.path || '').trim();
      if (!path) continue;

      let action: 'created' | 'modified' | 'deleted' | null = null;
      if (step.type === 'tool_result' || step.type === 'tool_call') {
        action = normalizeFileAction(data?.action || args?.action || step.name);
      }

      if (!action) continue;
      const existingIndex = collected.findIndex((entry) => entry.path === path);
      const nextEntry = { path, action };
      if (existingIndex >= 0) {
        collected.splice(existingIndex, 1);
      }
      collected.push(nextEntry);
    }

    for (const diffEntry of versionDiff?.filesChanged || []) {
      const path = String(diffEntry.path || '').trim();
      if (!path) continue;
      const action = normalizeFileAction(diffEntry.action);
      const existingIndex = collected.findIndex((entry) => entry.path === path);
      const nextEntry = { path, action };
      if (existingIndex >= 0) {
        collected.splice(existingIndex, 1);
      }
      collected.push(nextEntry);
    }

    return collected.slice(-4).reverse();
  }, [steps, versionDiff]);

  const timelinePreview = useMemo(
    () => visibleTimelineEvents.slice(-3).reverse().map((event) => prettifyTimelineLabel(event)),
    [visibleTimelineEvents]
  );

  const activityCardStatus: 'streaming' | 'success' | 'failed' | 'cancelled' | null = isStreaming
    ? 'streaming'
    : runSummary?.status === 'success'
      ? 'success'
      : runSummary?.status === 'failed'
        ? 'failed'
        : runSummary?.status === 'cancelled'
          ? 'cancelled'
          : null;

  const activityCardCurrentAction = isStreaming
    ? formatLiveStepLabel(liveCurrentStep)
    : timelinePreview[0] || 'История этого запуска сохранена в чате.';

  const detailBlockTypes = new Set(['thought', 'plan', 'tools', 'read', 'edit', 'edits', 'db_logs', 'validation']);
  const primaryBlocks = blocks.filter((block) => !detailBlockTypes.has(block.type));
  const detailBlocks = blocks.filter((block) => detailBlockTypes.has(block.type));

  const renderBlock = (block: (typeof blocks)[number], idx: number, keyPrefix = '') => (
    <motion.div
      key={`${keyPrefix}${block.type}-${idx}`}
      initial={{ opacity: 0, y: 5 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -5 }}
      transition={{ delay: idx * 0.05 }}
    >
      {block.type === 'thought' && block.duration && (
        <ThoughtBadge duration={block.duration} />
      )}
      
      {block.type === 'text' && block.content && (
        <div className="text-sm text-foreground leading-relaxed whitespace-pre-wrap">
          {enableTextStreaming ? (
            <StreamingTextByWord 
              text={block.content} 
              speed={30}
              skipAnimation={!isStreaming}
            />
          ) : (
            block.content
          )}
        </div>
      )}

      {block.type === 'plan' && block.plan && (
        <PlanCard title={block.plan.title} tasks={block.plan.tasks} />
      )}
      
      {block.type === 'tools' && block.tools && (
        <ToolsUsedBadge 
          count={block.count || 0} 
          tools={block.tools}
          allSteps={steps}
        />
      )}
      
      {block.type === 'read' && block.filename && (
        <ReadBadge filename={block.filename} />
      )}
      
      {block.type === 'edit' && block.filename && (
        <EditingBadge filename={block.filename} />
      )}
      
      {block.type === 'edits' && block.edits && (
        <EditsMadeBadge count={block.count || 0} edits={block.edits} />
      )}
      
      {block.type === 'db_logs' && block.logType && (
        <ReadDatabaseLogsBadge logType={block.logType} />
      )}
      
      {block.type === 'database' && block.migration && (
        block.migration.autoGenerated ? (
          <AutoMigrationCard 
            migration={{
              id: 'pending-auto-migration',
              sql: block.migration.sql,
              description: block.migration.description,
              tables: block.migration.tables,
              status: block.migration.status || 'pending',
              autoGenerated: true,
              requiresAuth: block.migration.requiresAuth,
              features: block.migration.features,
              result: block.migration.result,
            }}
            onApprove={() => onMigrationApprove?.()}
            onReject={() => onMigrationReject?.()}
            isProcessing={block.migration.status === 'executing'}
          />
        ) : (
          <DatabaseModifiedBadge 
            migration={block.migration}
            status={block.migration.status}
            result={block.migration.result}
            onApprove={onMigrationApprove}
            onReject={onMigrationReject}
          />
        )
      )}
      
      {block.type === 'validation' && block.validationData && (
        <ValidationBadge validation={block.validationData} />
      )}
      
    </motion.div>
  );

  return (
    <div className="space-y-1.5">
      {runSummary && (
        <div className="flex justify-end">
          <RunSummaryPopover summary={runSummary} />
        </div>
      )}

      {activityCardStatus && (
        <LiveGenerationCard
          statusText={isStreaming ? liveStatusText : humanizeRunStatus(runSummary?.status, isStreaming)}
          currentAction={activityCardCurrentAction}
          fileActions={liveFileActions}
          status={activityCardStatus}
          timelinePreview={timelinePreview}
        />
      )}

      <AnimatePresence mode="popLayout">
        {primaryBlocks.map((block, idx) => renderBlock(block, idx))}
      </AnimatePresence>

      {detailBlocks.length > 0 && (
        <Collapsible open={showDetails} onOpenChange={setShowDetails}>
          <CollapsibleTrigger asChild>
            <button className="flex w-full items-center gap-2 rounded-md border border-border/60 bg-background/40 px-2.5 py-1.5 text-xs text-muted-foreground hover:bg-muted/40 transition-colors">
              <ShieldCheck className="w-3.5 h-3.5" />
              <span>Детали ({detailBlocks.length})</span>
              <span className="ml-auto">
                {showDetails ? <ChevronUp className="w-3.5 h-3.5" /> : <ChevronDown className="w-3.5 h-3.5" />}
              </span>
            </button>
          </CollapsibleTrigger>
          <CollapsibleContent>
            <div className="mt-2 space-y-1.5 rounded-md border border-border/50 bg-muted/20 p-2.5">
              <AnimatePresence mode="popLayout">
                {detailBlocks.map((block, idx) => renderBlock(block, idx, 'detail-'))}
              </AnimatePresence>
            </div>
          </CollapsibleContent>
        </Collapsible>
      )}

      {visibleTimelineEvents.length > 0 && (
        <div className="rounded-md border border-border/60 bg-muted/20 px-3 py-2">
          <div className="mb-2 flex items-center justify-between gap-2">
            <div className="text-xs font-medium text-foreground">Хронология</div>
            {!showDetails ? (
              <div className="text-[11px] text-muted-foreground">Открой детали для полного списка шагов</div>
            ) : null}
          </div>
          <div className="space-y-1.5">
            <AnimatePresence initial={false}>
              {(showDetails ? visibleTimelineEvents : visibleTimelineEvents.slice(-3)).map((event, index, items) => (
                <motion.div
                  key={event.id}
                  layout
                  initial={{ opacity: 0, x: -8 }}
                  animate={{ opacity: 1, x: 0 }}
                  exit={{ opacity: 0, x: 8 }}
                  transition={{ duration: 0.18, delay: index * 0.03 }}
                  className="flex items-start gap-2 text-xs"
                >
                  <motion.span
                    animate={
                      index === items.length - 1
                        ? { scale: [1, 1.35, 1], opacity: [0.75, 1, 0.75] }
                        : undefined
                    }
                    transition={{ duration: 1.4, repeat: Infinity, ease: 'easeInOut' }}
                    className={cn(
                      "mt-0.5 inline-block h-1.5 w-1.5 rounded-full",
                      event.status === 'success' && 'bg-green-500',
                      event.status === 'error' && 'bg-red-500',
                      event.status === 'info' && 'bg-blue-500'
                    )}
                  />
                  <span className="text-muted-foreground">
                    {prettifyTimelineLabel(event)}
                    {event.path ? ` • ${event.path.split('/').pop()}` : ''}
                  </span>
                </motion.div>
              ))}
            </AnimatePresence>
          </div>
        </div>
      )}

      {/* Auto-fix indicator - shown at the bottom during auto-fixing */}
      {autoFix && (autoFix.isAutoFixing || autoFix.attempt > 0) && (
        <AutoFixIndicator
          isAutoFixing={autoFix.isAutoFixing}
          attempt={autoFix.attempt}
          maxAttempts={autoFix.maxAttempts}
          currentScore={autoFix.currentScore}
        />
      )}
    </div>
  );
}

export default AgentStreamBlocks;
