/**
 * 🔧 StepsMessage Component
 * Displays assistant messages with agent steps using AgentStreamBlocks
 * Text answer first, then collapsible badges
 */
import { motion } from 'framer-motion';
import { AgentStreamBlocks } from './AgentStreamBlocks';
import type { RunSummary } from './RunSummaryCard';
import type { ChatTimelineEvent, ChatVersionDiff } from '@/lib/chat-ui-event-contract';
import { cn } from '@/lib/utils';
import type { AgentStep, PendingMigration } from '@/hooks/useUnifiedOrchestrator';

interface StepsMessageProps {
  content: string;
  steps: AgentStep[];
  runSummary?: RunSummary;
  timelineEvents?: ChatTimelineEvent[];
  versionDiff?: ChatVersionDiff | null;
  timestamp?: number;
  className?: string;
  animationDelay?: number;
  isStreaming?: boolean;
  enableTextStreaming?: boolean;
  pendingMigration?: PendingMigration;
  onMigrationApprove?: () => void;
  onMigrationReject?: () => void;
}

export function StepsMessage({ 
  content,
  steps,
  runSummary,
  timelineEvents,
  versionDiff,
  timestamp,
  className,
  animationDelay = 0,
  isStreaming = false,
  enableTextStreaming = false,
  pendingMigration,
  onMigrationApprove,
  onMigrationReject
}: StepsMessageProps) {
  const thinkingStep = steps.find(s => s.type === 'thinking');
  
  // Check if we have any meaningful content to show
  const hasContent =
    content?.trim() ||
    steps.length > 0 ||
    Boolean(runSummary) ||
    Boolean(versionDiff) ||
    Boolean(timelineEvents?.length);
  
  if (!hasContent && !isStreaming) {
    return null;
  }
  
  return (
    <motion.div 
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.2, delay: animationDelay * 0.05 }}
      className={cn("flex", className)}
    >
      {/* Content container */}
      <div className="flex-1 max-w-[85%] space-y-2 rounded-2xl rounded-tl-sm border border-border/60 bg-card/70 px-3 py-2.5 shadow-sm">
        <AgentStreamBlocks
          steps={steps}
          textContent={content}
          runSummary={runSummary}
          timelineEvents={timelineEvents}
          versionDiff={versionDiff}
          thinkingDuration={thinkingStep?.duration}
          isStreaming={isStreaming}
          enableTextStreaming={enableTextStreaming}
          pendingMigration={pendingMigration ? {
            sql: pendingMigration.sql,
            description: pendingMigration.description,
            tables: pendingMigration.tables,
            status: pendingMigration.status,
            result: pendingMigration.result,
            autoGenerated: pendingMigration.autoGenerated,
            requiresAuth: pendingMigration.requiresAuth,
            features: pendingMigration.features,
          } : undefined}
          onMigrationApprove={onMigrationApprove}
          onMigrationReject={onMigrationReject}
        />
        
        {/* Timestamp */}
        {timestamp && !isStreaming && (
          <div className="text-[10px] text-muted-foreground pt-1">
            {new Date(timestamp).toLocaleTimeString('ru-RU', { 
              hour: '2-digit', 
              minute: '2-digit' 
            })}
          </div>
        )}
      </div>
    </motion.div>
  );
}
