import { useState, useCallback, useRef } from "react";
import { isApiConfigured } from "@/lib/api-client";
import { runUnifiedOrchestratorStream } from "@/features/builder/api/unified-orchestrator-api";
import { toUserFacingGenerationErrorContract } from "@/features/builder/run/user-facing-error";
import type {
  PipelineMode as BasePipelineMode,
  PipelinePhase as BasePipelinePhase,
  ComplexityLevel,
  StepStatus,
  RequirementsSpec,
  Plan,
  Epic,
  PipelineStep,
  PipelineMetrics,
  ValidationResult as BaseValidationResult,
} from "@/types/pipeline";

/**
 * Unified Orchestrator Hook
 * 
 * Single orchestrator with 4 modes:
 * - LIGHT: Execute -> Validate (fast -> fast) - micro-tasks
 * - LOW: Execute -> Validate (balanced -> fast) - simple tasks
 * - MEDIUM: Plan -> Execute -> Validate (balanced -> balanced -> fast) - standard
 * - HIGH: Plan -> Execute -> Validate (premium -> balanced -> fast) - complex
 * 
 * + EPIC mode for long prompts (500+ words):
 *   Intake → Analyze → Plan → [Stage_N...] → Validate → Preview
 */

// Re-export types for backward compatibility
export type PipelineMode = BasePipelineMode;
export type PipelinePhase = BasePipelinePhase | 'plan' | 'execute' | 'validate';

export interface BuilderContext {
  environment: 'builder' | 'dashboard' | 'landing' | 'create_project' | 'unknown';
  hasProject: boolean;
  projectName?: string;
  projectId?: string;
  projectSessionId?: string;
  projectType?: 'website' | 'tma' | 'landing' | 'webapp';
  runKind?: 'initial' | 'iterative';
  existingFiles?: string[];
  existingPackages?: string[];
  recentMessages?: string[];
  conversationState?: {
    latestUserRequest?: string;
    previousUserRequest?: string;
    lastAssistantMessage?: string;
    projectGoal?: string;
    activeIssue?: string;
    conversationLanguage?: string;
  };
  currentFocus?: 'code' | 'preview' | 'chat' | 'settings';
  preprocessedIntent?: {
    actionType: string;
    target: string;
    complexity: ComplexityLevel;
    language?: string;
    forceDeepReview?: boolean;
    minQualityScore?: number;
    recreateFromScratch?: boolean; // 🆕 When true, clears all files and creates from scratch
    planDetailLevel?: 'none' | 'micro' | 'standard' | 'detailed';
    planTaskLimit?: number;
  };
  // New: for long prompts
  requirementsSpec?: Partial<RequirementsSpec>;
  plan?: Partial<Plan>;
}

export interface AgentStep {
  id: string;
  type:
    | "phase"
    | "tool_call"
    | "tool_result"
    | "text"
    | "error"
    | "plan"
    | "validation"
    | "thinking"
    | "complete"
    | "internal_event"
    | "intake"
    | "epic"
    | "story"
    | "task";
  name?: string;
  content?: string;
  phase?: PipelinePhase;
  model?: string;
  success?: boolean;
  data?: unknown;
  args?: unknown;
  duration?: number;
  timestamp: number;
  // New: for epic tracking
  epicId?: string;
  storyId?: string;
  taskId?: string;
  progress?: number;
}

export interface AgentFile {
  path: string;
  content: string;
  action: "created" | "modified" | "deleted";
}

export interface MigrationResult {
  success: boolean;
  message?: string;
  results?: Array<{ statement: string; success: boolean; error?: string }>;
}

export interface PendingMigration {
  id: string;
  sql: string;
  description?: string;
  tables?: string[];
  status: 'pending' | 'approved' | 'rejected' | 'executing' | 'completed' | 'failed';
  result?: MigrationResult;
  // 🆕 Auto-generated migrations from LLM backend detection
  autoGenerated?: boolean;
  requiresAuth?: boolean;
  features?: string[];
}

export interface ValidationSummary {
  errors: number;
  warnings: number;
  info: number;
}

export interface ValidationState {
  valid: boolean;
  score: number;
  summary: ValidationSummary;
  issuesByCategory?: Record<string, Array<{
    type: string;
    file: string;
    message: string;
    suggestion?: string;
    line?: number;
  }>>;
}

export interface EpicProgress {
  epicId: string;
  epicIndex: number;
  totalEpics: number;
  title: string;
  storiesCount: number;
  currentStory?: number;
  status: 'pending' | 'active' | 'completed' | 'failed';
}

export interface UnifiedState {
  isRunning: boolean;
  error: string | null;
  runtimeBuildGateLog: string | null;
  
  // Mode & phases
  mode: PipelineMode | null;
  phases: PipelinePhase[];
  currentPhase: PipelinePhase | null;
  
  // Progress
  iteration: number;
  maxIterations: number;
  
  // Plan (if MEDIUM/HIGH mode)
  architecture: string | null;
  tasks: string[];
  
  // Epic mode tracking (NEW)
  isEpicMode: boolean;
  epics: EpicProgress[];
  currentEpicIndex: number;
  epicProgress: number; // 0-100
  requirements?: {
    goals: string[];
    constraints: string[];
    integrations: string[];
    complexity?: {
      level: ComplexityLevel;
      score: number;
    };
  };
  
  // Validation (enhanced)
  issues: string[];
  fixes: number;
  validation: ValidationState | null;
  
  // Auto-fix tracking (enhanced)
  autoFixAttempt: number;
  autoFixMaxAttempts: number;
  isAutoFixing: boolean;
  autoFixScore: number;
  autoFixPreviousScore: number;
  autoFixFilesFixed: string[];
  autoFixErrorCount: number;
  
  // Output
  steps: AgentStep[];
  files: Record<string, string>;
  packages: string[];
  textOutput: string;
  
  // Database migrations
  pendingMigration: PendingMigration | null;
  
  // 🆕 Auto-recovery snapshot
  recoverySnapshotId: string | null;
  recoverySnapshotFileCount: number;
  isRecovering: boolean;
  
  // Result
  completed: boolean;
  lastVersion?: {
    id: string;
    version_number: number;
    message: string | null;
  };

  // Operator contract runtime view (Phase 8)
  operatorTimeline: Array<{
    id: string;
    eventType: string;
    key?: string;
    ts: number;
    payload?: unknown;
  }>;
  runtimePolicies: Record<string, unknown>;
  phase8: {
    tenantId: string | null;
    capabilityStatus: string | null;
    lastPolicyKey: string | null;
  };
}

interface UseUnifiedOrchestratorOptions {
  onStep?: (step: AgentStep) => void;
  onFileChange?: (file: AgentFile) => void;
  onPhaseChange?: (phase: PipelinePhase, model: string) => void;
  onComplete?: (state: UnifiedState) => void;
  onError?: (error: string) => void;
}

const initialState: UnifiedState = {
  isRunning: false,
  error: null,
  runtimeBuildGateLog: null,
  mode: null,
  phases: [],
  currentPhase: null,
  iteration: 0,
  maxIterations: 8,
  architecture: null,
  tasks: [],
  // Epic mode
  isEpicMode: false,
  epics: [],
  currentEpicIndex: 0,
  epicProgress: 0,
  requirements: undefined,
  // Validation
  issues: [],
  fixes: 0,
  validation: null,
  autoFixAttempt: 0,
  autoFixMaxAttempts: 2,
  isAutoFixing: false,
  autoFixScore: 0,
  autoFixPreviousScore: 0,
  autoFixFilesFixed: [],
  autoFixErrorCount: 0,
  steps: [],
  files: {},
  packages: [],
  textOutput: "",
  pendingMigration: null,
  // 🆕 Auto-recovery
  recoverySnapshotId: null,
  recoverySnapshotFileCount: 0,
  isRecovering: false,
  completed: false,
  lastVersion: undefined,
  operatorTimeline: [],
  runtimePolicies: {},
  phase8: {
    tenantId: null,
    capabilityStatus: null,
    lastPolicyKey: null,
  },
};

function normalizeLogsTail(raw: unknown): string | null {
  const text = String(raw || "").trim();
  if (!text) return null;
  const lines = text.split(/\r?\n/).filter(Boolean);
  return lines.slice(-20).join("\n");
}

function normalizeFailureToken(value: unknown): string | null {
  const token = String(value || "")
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9_]+/g, "_")
    .replace(/^_+|_+$/g, "");
  return token || null;
}

function buildToolResultErrorContent(event: Record<string, unknown>): string {
  const errorCode = normalizeFailureToken(event.errorCode);
  const stage = normalizeFailureToken(event.stage);
  const shortReason = normalizeFailureToken(event.shortReason);

  const details: string[] = [];
  if (errorCode) details.push(`код: ${errorCode}`);
  if (stage) details.push(`этап: ${stage}`);
  if (shortReason) details.push(`причина: ${shortReason}`);
  if (details.length > 0) {
    return `Ошибка действия (${details.join(" · ")})`;
  }
  return "Ошибка действия";
}

function asObject(value: unknown): Record<string, unknown> {
  return value && typeof value === 'object' ? (value as Record<string, unknown>) : {};
}

function normalizeAssistantText(text: unknown): string | null {
  const value = String(text || '')
    .replace(/\s+/g, ' ')
    .trim();
  return value ? value : null;
}

function looksLikeRawPipelineText(text: string): boolean {
  return (
    !text ||
    text.startsWith('{') ||
    text.startsWith('[') ||
    /"operations"\s*:|"action"\s*:|"path"\s*:|"packages"\s*:|"content"\s*:/.test(text) ||
    /\b(?:phase|iteration|tool|runtime|validation|quality[_ -]?gate|pipeline|operator|json|retry|attempt|recovery)\b/i.test(text) ||
    /json_contract_|late_json_truncation_recovery|schema_overflow_recovery|tool_contract_/i.test(text)
  );
}

function shouldAcceptAssistantDelta(text: unknown): boolean {
  const value = normalizeAssistantText(text);
  if (!value) return false;
  if (value.length < 12) return false;
  if (looksLikeRawPipelineText(value)) return false;
  return /[a-zа-яё]/i.test(value);
}

function setAssistantText(current: string, next: unknown): string {
  const normalized = normalizeAssistantText(next);
  if (!normalized) return current;
  return normalized === current ? current : normalized;
}

function appendAssistantText(current: string, next: unknown): string {
  const normalized = normalizeAssistantText(next);
  if (!normalized) return current;
  if (!current) return normalized;
  if (current.includes(normalized) || normalized.includes(current)) return normalized;
  return `${current} ${normalized}`.trim();
}

function describeAssistantStreamEvent(
  event: Record<string, unknown>,
  _prev: UnifiedState
): { mode: 'replace' | 'append'; text: string } | null {
  const eventType = String(event.type || '');

  if (eventType === 'assistant_reply') {
    const content = String(event.content || '');
    return shouldAcceptAssistantDelta(content)
      ? { mode: 'replace', text: content }
      : null;
  }

  if (eventType === 'assistant_reply_delta') {
    const delta = String(event.text || event.content || '');
    return shouldAcceptAssistantDelta(delta)
      ? { mode: 'append', text: delta }
      : null;
  }

  return null;
}

export function useUnifiedOrchestrator(options: UseUnifiedOrchestratorOptions = {}) {
  const { onStep, onFileChange, onPhaseChange, onComplete, onError } = options;
  
  const [state, setState] = useState<UnifiedState>(initialState);
  const abortControllerRef = useRef<AbortController | null>(null);
  
  // Refs for callbacks
  const callbackRefs = useRef({ onStep, onFileChange, onPhaseChange, onComplete, onError });
  callbackRefs.current = { onStep, onFileChange, onPhaseChange, onComplete, onError };

  const processEvent = useCallback((event: Record<string, unknown>) => {
    const timestamp = Date.now();
    const eventType = event.type as string;

    setState(prev => {
      // Pipeline start
      if (eventType === 'pipeline_start') {
        const assistantStream = describeAssistantStreamEvent(event, prev);
        return {
          ...prev,
          mode: event.mode as PipelineMode,
          phases: event.phases as PipelinePhase[],
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
        };
      }

      if (eventType === 'runtime_policy') {
        const key = typeof event.key === 'string' ? event.key : '';
        const timelineEvent = {
          id: `runtime-policy-${timestamp}-${prev.operatorTimeline.length + 1}`,
          eventType,
          key: key || undefined,
          ts: timestamp,
          payload: event,
        };
        const nextTimeline = [...prev.operatorTimeline, timelineEvent].slice(-250);
        const nextPolicies =
          key.length > 0
            ? { ...prev.runtimePolicies, [key]: event }
            : prev.runtimePolicies;

        const nextPhase8 = { ...prev.phase8 };
        const tenantId = (event.tenantId as string | undefined) || null;
        if (tenantId && typeof tenantId === 'string') {
          nextPhase8.tenantId = tenantId;
        }
        if (key === 'eligibility_matrix') {
          nextPhase8.capabilityStatus =
            typeof event.status === 'string' ? (event.status as string) : nextPhase8.capabilityStatus;
        }
        if (key) nextPhase8.lastPolicyKey = key;

        return {
          ...prev,
          operatorTimeline: nextTimeline,
          runtimePolicies: nextPolicies,
          phase8: nextPhase8,
        };
      }

      if (eventType === 'stream_transport') {
        const timelineEvent = {
          id: `stream-transport-${timestamp}-${prev.operatorTimeline.length + 1}`,
          eventType,
          key: String(event.selected || 'sse'),
          ts: timestamp,
          payload: event,
        };
        return {
          ...prev,
          operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
        };
      }

      if (
        eventType === 'backend_decision' ||
        eventType === 'backend_schema_plan' ||
        eventType === 'backend_migration_compiled' ||
        eventType === 'backend_migration_compile_failed' ||
        eventType === 'backend_migration_compile_skipped' ||
        eventType === 'backend_migration_apply_result' ||
        eventType === 'backend_migration_apply_failed' ||
        eventType === 'backend_migration_apply_skipped' ||
        eventType === 'backend_provisioned' ||
        eventType === 'backend_provision_failed' ||
        eventType === 'backend_provision_skipped'
      ) {
        const timelineEvent = {
          id: `${eventType}-${timestamp}-${prev.operatorTimeline.length + 1}`,
          eventType,
          key: undefined,
          ts: timestamp,
          payload: event,
        };

        let content = '';
        if (eventType === 'backend_decision') {
          const required = Boolean(event.required);
          const confidence = String(event.confidence || 'low');
          content = required
            ? `Backend decision: включить backend (${confidence})`
            : `Backend decision: frontend-only (${confidence})`;
        } else if (eventType === 'backend_schema_plan') {
          const summary = asObject(event.summary);
          const tableCount = Number(summary.tableCount || 0);
          const features = summary.features;
          const featureCount = Array.isArray(features)
            ? features.length
            : 0;
          content = `Backend schema plan: ${tableCount} table(s), ${featureCount} feature signal(s)`;
        } else if (eventType === 'backend_migration_compiled') {
          const summary = asObject(event.summary);
          const applyCount = Number(summary.applyStatements || 0);
          content = `Backend migration compiled: ${applyCount} SQL statement(s)`;
        } else if (eventType === 'backend_migration_compile_failed') {
          content = `Backend migration compile failed: ${String(event.code || 'unknown')}`;
        } else if (eventType === 'backend_migration_compile_skipped') {
          content = `Backend migration compile skipped: ${String(event.reason || 'unknown')}`;
        } else if (eventType === 'backend_migration_apply_result') {
          const summary = asObject(event.summary);
          content = `Backend migration apply result: ${String(summary.status || 'unknown')}`;
        } else if (eventType === 'backend_migration_apply_failed') {
          content = `Backend migration apply failed: ${String(event.code || 'unknown')}`;
        } else if (eventType === 'backend_migration_apply_skipped') {
          content = `Backend migration apply skipped: ${String(event.reason || 'unknown')}`;
        } else if (eventType === 'backend_provisioned') {
          content = `Backend provisioned (${event.reused ? 'reused' : 'created'})`;
        } else if (eventType === 'backend_provision_failed') {
          content = `Backend provision failed: ${String(event.code || 'unknown')}`;
        } else if (eventType === 'backend_provision_skipped') {
          content = `Backend provision skipped: ${String(event.reason || 'unknown')}`;
        }

        if (!content) {
          return {
            ...prev,
            operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
          };
        }
        return {
          ...prev,
          operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
        };
      }

      if (
        eventType === 'model_retry' ||
        eventType === 'model_fallback' ||
        eventType === 'fallback_applied'
      ) {
        const timelineEvent = {
          id: `${eventType}-${timestamp}-${prev.operatorTimeline.length + 1}`,
          eventType,
          key: undefined,
          ts: timestamp,
          payload: event,
        };
        return {
          ...prev,
          operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
        };
      }

      if (eventType === 'internal_event') {
        const eventName = String(event.eventName || '').trim();
        const status = String(event.status || '').trim().toLowerCase();
        const timelineEvent = {
          id: `${eventType}-${timestamp}-${prev.operatorTimeline.length + 1}`,
          eventType,
          key: eventName || undefined,
          ts: timestamp,
          payload: event,
        };

        if (eventName !== 'task_completion') {
          return {
            ...prev,
            operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
          };
        }
        return {
          ...prev,
          operatorTimeline: [...prev.operatorTimeline, timelineEvent].slice(-250),
        };
      }

      // Phase transitions
      if (eventType === 'phase_start') {
        const phase = event.phase as PipelinePhase;
        const model = event.model as string;
        const assistantStream = describeAssistantStreamEvent(event, prev);
        callbackRefs.current.onPhaseChange?.(phase, model);

        return {
          ...prev,
          currentPhase: phase,
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
        };
      }

      if (eventType === 'phase_complete') {
        return prev;
      }

      if (eventType === 'quality_pass_warning') {
        const message = String(
          event.message || 'Quality gate ниже целевого уровня; применен стабилизационный каркас'
        );
        const assistantStream = describeAssistantStreamEvent(event, prev);
        const step: AgentStep = {
          id: `quality-warning-${timestamp}`,
          type: 'thinking',
          content: `⚠️ ${message}`,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        return {
          ...prev,
          steps: [...prev.steps, step],
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
          operatorTimeline: [
            ...prev.operatorTimeline,
            {
              id: `quality-warning-timeline-${timestamp}`,
              eventType,
              ts: timestamp,
              payload: event,
            },
          ].slice(-250),
        };
      }

      if (eventType === 'runtime_build_gate') {
        const pass = Boolean(event.pass);
        const logsTail = normalizeLogsTail(event.logsTail);
        const assistantStream = describeAssistantStreamEvent(event, prev);
        if (pass) return prev;

        const step: AgentStep = {
          id: `runtime-build-gate-${timestamp}`,
          type: 'error',
          content: '❌ Проверка сборки не пройдена. Генерация остановлена до исправления.',
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        return {
          ...prev,
          runtimeBuildGateLog: logsTail || prev.runtimeBuildGateLog,
          steps: [...prev.steps, step],
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
          operatorTimeline: [
            ...prev.operatorTimeline,
            {
              id: `runtime-build-gate-timeline-${timestamp}`,
              eventType,
              ts: timestamp,
              payload: event,
            },
          ].slice(-250),
        };
      }

      if (eventType === 'runtime_build_gate_log') {
        const logsTail = normalizeLogsTail(event.logsTail);
        return {
          ...prev,
          runtimeBuildGateLog: logsTail || prev.runtimeBuildGateLog,
          operatorTimeline: [
            ...prev.operatorTimeline,
            {
              id: `runtime-build-gate-log-timeline-${timestamp}`,
              eventType,
              ts: timestamp,
              payload: event,
            },
          ].slice(-250),
        };
      }

      // Requirements parsed (epic mode)
      if (eventType === 'requirements_parsed') {
        const requirements = event.requirements as UnifiedState['requirements'];
        return {
          ...prev,
          requirements,
        };
      }

      // Plan created
      if (eventType === 'plan_created') {
        const epicsData = event.epics as Array<{
          id: string;
          title: string;
          storiesCount: number;
        }> | undefined;
        
        const isEpicMode = !!epicsData && epicsData.length > 0;
        
        const step: AgentStep = {
          id: `plan-${timestamp}`,
          type: 'plan',
          content: event.architecture as string,
          data: { 
            tasks: event.tasks, 
            epics: epicsData,
            totalTasks: event.totalTasks,
            estimatedDuration: event.estimatedDuration,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          isEpicMode,
          architecture: event.architecture as string,
          tasks: event.tasks as string[],
          epics: isEpicMode 
            ? epicsData.map((e, i) => ({
                epicId: e.id,
                epicIndex: i,
                totalEpics: epicsData.length,
                title: e.title,
                storiesCount: e.storiesCount,
                status: 'pending' as const,
              }))
            : [],
          steps: [...prev.steps, step],
        };
      }

      // Epic start
      if (eventType === 'epic_start') {
        const epicId = event.epicId as string;
        const epicIndex = event.epicIndex as number;
        
        const step: AgentStep = {
          id: `epic-${epicId}-${timestamp}`,
          type: 'epic',
          name: event.title as string,
          content: event.description as string,
          epicId,
          progress: 0,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          currentEpicIndex: epicIndex,
          epics: prev.epics.map((e, i) => ({
            ...e,
            status: i === epicIndex ? 'active' : i < epicIndex ? 'completed' : 'pending',
          })),
          steps: [...prev.steps, step],
        };
      }

      // Epic complete
      if (eventType === 'epic_complete') {
        const epicId = event.epicId as string;
        
        return {
          ...prev,
          epics: prev.epics.map(e => ({
            ...e,
            status: e.epicId === epicId ? 'completed' : e.status,
          })),
        };
      }

      // Epic progress
      if (eventType === 'epic_progress') {
        return {
          ...prev,
          epicProgress: event.progress as number,
        };
      }

      // Story start
      if (eventType === 'story_start') {
        const step: AgentStep = {
          id: `story-${event.storyId}-${timestamp}`,
          type: 'story',
          name: event.title as string,
          epicId: event.epicId as string,
          storyId: event.storyId as string,
          progress: 0,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          epics: prev.epics.map(e => 
            e.epicId === event.epicId 
              ? { ...e, currentStory: event.storyIndex as number }
              : e
          ),
          steps: [...prev.steps, step],
        };
      }

      // Story complete
      if (eventType === 'story_complete') {
        return prev;
      }

      // Iterations
      if (eventType === 'iteration_start') {
        const assistantStream = describeAssistantStreamEvent(event, prev);
        return {
          ...prev,
          iteration: event.iteration as number,
          maxIterations: event.maxIterations as number,
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
        };
      }

      if (eventType === 'text') {
        return prev;
      }

      if (eventType === 'text_delta') {
        return prev;
      }

      // Tool calls
      if (eventType === 'tool_start') {
        const assistantStream = describeAssistantStreamEvent(event, prev);
        const step: AgentStep = {
          id: event.id as string,
          type: 'tool_call',
          name: event.name as string,
          data: event.args,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        return {
          ...prev,
          steps: [...prev.steps, step],
          textOutput:
            assistantStream?.mode === 'append'
              ? appendAssistantText(prev.textOutput, assistantStream.text)
              : setAssistantText(prev.textOutput, assistantStream?.text),
        };
      }

      if (eventType === 'tool_result') {
        const data = event.data as
          | { path?: string; content?: string; action?: string }
          | undefined;
        const toolResultMeta = {
          ...(data || {}),
          errorCode: normalizeFailureToken(event.errorCode),
          stage: normalizeFailureToken(event.stage),
          shortReason: normalizeFailureToken(event.shortReason),
        };

        // Handle file changes
        if (data?.path && data?.action) {
          callbackRefs.current.onFileChange?.({
            path: data.path,
            content: data.content || '',
            action: data.action as 'created' | 'modified' | 'deleted',
          });
        }

        const stepIndex = prev.steps.findIndex(s => s.id === event.id);
        if (stepIndex >= 0) {
          const updatedStep: AgentStep = {
            ...prev.steps[stepIndex],
            type: 'tool_result',
            success: event.success as boolean,
            content:
              event.success === false
                ? buildToolResultErrorContent(event)
                : (event.result as string),
            data: toolResultMeta,
          };
          const newSteps = [...prev.steps];
          newSteps[stepIndex] = updatedStep;
          callbackRefs.current.onStep?.(updatedStep);
          return { ...prev, steps: newSteps };
        }

        const fallbackStep: AgentStep = {
          id: String(event.id || `tool-result-${timestamp}`),
          type: 'tool_result',
          name: String(event.name || event.tool || 'tool_result'),
          success: event.success as boolean,
          content:
            event.success === false
              ? buildToolResultErrorContent(event)
              : String(event.result || 'Действие выполнено'),
          data: toolResultMeta,
          timestamp,
        };
        callbackRefs.current.onStep?.(fallbackStep);
        return {
          ...prev,
          steps: [...prev.steps, fallbackStep],
        };
      }

      // Validation category (new event for detailed validation)
      if (eventType === 'validation_category') {
        const category = event.category as string;
        const issues = event.issues as Array<{
          type: string;
          file: string;
          message: string;
          suggestion?: string;
          line?: number;
        }>;
        
        return {
          ...prev,
          validation: {
            ...prev.validation,
            valid: prev.validation?.valid ?? true,
            score: prev.validation?.score ?? 100,
            summary: prev.validation?.summary ?? { errors: 0, warnings: 0, info: 0 },
            issuesByCategory: {
              ...prev.validation?.issuesByCategory,
              [category]: issues,
            },
          },
        };
      }

      // Validation result (enhanced)
      if (eventType === 'validation_result') {
        const validationState: ValidationState = {
          valid: event.valid as boolean ?? true,
          score: event.score as number ?? 100,
          summary: event.summary as ValidationSummary ?? { errors: 0, warnings: 0, info: 0 },
          issuesByCategory: prev.validation?.issuesByCategory,
        };
        
        const message = event.message as string || 
          `${(event.issues as string[])?.length || 0} issues, ${event.fixes} auto-fixes`;
        
        const step: AgentStep = {
          id: `validation-${timestamp}`,
          type: 'validation',
          content: message,
          success: validationState.valid,
          data: { 
            issues: event.issues, 
            fixes: event.fixes,
            score: validationState.score,
            summary: validationState.summary,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          issues: event.issues as string[],
          fixes: event.fixes as number,
          validation: validationState,
          steps: [...prev.steps, step],
        };
      }

      // Version created
      if (eventType === 'version_created') {
        const version = event.version as { id: string; version_number: number; message: string | null };
        return { ...prev, lastVersion: version };
      }

      // 🆕 Snapshot created for auto-recovery
      if (eventType === 'snapshot_created') {
        console.log('[UnifiedOrchestrator] 📸 Recovery snapshot created:', event.snapshotId);
        return { 
          ...prev, 
          recoverySnapshotId: event.snapshotId as string,
          recoverySnapshotFileCount: event.fileCount as number || 0,
        };
      }

      // Migration pending approval
      if (eventType === 'migration_pending') {
        const migration: PendingMigration = {
          id: event.id as string || `migration-${timestamp}`,
          sql: event.sql as string,
          description: event.description as string | undefined,
          tables: event.tables as string[] | undefined,
          status: 'pending',
          // 🆕 Auto-generated migrations from LLM backend detection
          autoGenerated: event.autoGenerated as boolean | undefined,
          requiresAuth: event.requiresAuth as boolean | undefined,
          features: event.features as string[] | undefined,
        };
        return { ...prev, pendingMigration: migration };
      }

      // Migration approved/rejected
      if (eventType === 'migration_approved') {
        return { 
          ...prev, 
          pendingMigration: prev.pendingMigration 
            ? { ...prev.pendingMigration, status: 'approved' } 
            : null 
        };
      }

      if (eventType === 'migration_rejected') {
        return { 
          ...prev, 
          pendingMigration: prev.pendingMigration 
            ? { ...prev.pendingMigration, status: 'rejected' } 
            : null 
        };
      }

      // Auto-fix events (enhanced)
      if (eventType === 'auto_fix_start') {
        const step: AgentStep = {
          id: `autofix-start-${timestamp}`,
          type: 'phase',
          name: 'auto_fix',
          content: `🔧 Auto-fix attempt ${event.attempt}/${event.maxAttempts} (score: ${event.score}, errors: ${event.errorCount || 0})`,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          isAutoFixing: true,
          autoFixAttempt: event.attempt as number,
          autoFixMaxAttempts: event.maxAttempts as number,
          autoFixScore: event.score as number,
          autoFixErrorCount: event.errorCount as number || 0,
          autoFixFilesFixed: [],
          steps: [...prev.steps, step],
        };
      }

      if (eventType === 'auto_fix_applied') {
        const file = event.file as string;
        return {
          ...prev,
          autoFixFilesFixed: [...prev.autoFixFilesFixed, file],
        };
      }

      if (eventType === 'auto_fix_complete') {
        const improved = event.improved as boolean;
        const step: AgentStep = {
          id: `autofix-complete-${timestamp}`,
          type: 'validation',
          success: improved,
          content: improved 
            ? `✅ Auto-fix успешен! Score: ${event.previousScore} → ${event.newScore} (+${(event.newScore as number) - (event.previousScore as number)})` 
            : `⚠️ Auto-fix попытка ${event.attempt}: score ${event.newScore}`,
          data: {
            previousScore: event.previousScore,
            newScore: event.newScore,
            improved,
            fixesApplied: event.fixesApplied,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          isAutoFixing: false,
          autoFixScore: event.newScore as number,
          autoFixPreviousScore: event.previousScore as number,
          fixes: event.fixesApplied as number || prev.fixes,
          steps: [...prev.steps, step],
        };
      }

      if (eventType === 'auto_fix_error') {
        const step: AgentStep = {
          id: `autofix-error-${timestamp}`,
          type: 'error',
          content: `❌ Auto-fix ошибка: ${event.error}`,
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          isAutoFixing: false,
          steps: [...prev.steps, step],
        };
      }

      // 🆕 Complete event - full summary step
      if (eventType === 'complete') {
        const step: AgentStep = {
          id: `complete-${timestamp}`,
          type: 'complete',
          name: 'Завершено',
          content: event.summary as string,
          success: true,
          data: {
            filesCreated: event.filesCreated,
            packagesInstalled: event.packagesInstalled,
            totalInputTokens: event.totalInputTokens,
            totalOutputTokens: event.totalOutputTokens,
            validation: event.validation,
            autoFixAttempts: event.autoFixAttempts,
            plan: event.plan,
            epicPlan: event.epicPlan,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        
        return {
          ...prev,
          steps: [...prev.steps, step],
        };
      }

      // Pipeline complete
      if (eventType === 'pipeline_complete') {
        const finalState: UnifiedState = {
          ...prev,
          isRunning: false,
          isAutoFixing: false,
          completed: event.success as boolean,
          files: event.files as Record<string, string>,
          packages: event.packages as string[],
        };
        callbackRefs.current.onComplete?.(finalState);
        return finalState;
      }

      // Error
      if (eventType === 'error') {
        const rawMessage = String(event.message || 'Unknown error');
        const contract = toUserFacingGenerationErrorContract({
          rawMessage,
          errorCode: event.errorCode,
          stage: event.stage,
          shortReason: event.shortReason,
        });
        callbackRefs.current.onError?.(contract.displayMessage);
        const step: AgentStep = {
          id: `error-${timestamp}`,
          type: 'error',
          content: contract.userMessage,
          success: false,
          data: {
            errorCode: contract.errorCode,
            stage: contract.stage,
            shortReason: contract.shortReason,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        return {
          ...prev,
          error: contract.displayMessage,
          isRunning: false,
          isAutoFixing: false,
          steps: [...prev.steps, step],
        };
      }

      if (eventType === 'terminal_failure') {
        const contract = toUserFacingGenerationErrorContract({
          rawMessage: String(event.displayMessage || event.message || ''),
          errorCode: event.errorCode,
          stage: event.stage,
          shortReason: event.shortReason,
        });
        const step: AgentStep = {
          id: `terminal-failure-${timestamp}`,
          type: 'error',
          content: contract.userMessage,
          success: false,
          data: {
            errorCode: contract.errorCode,
            stage: contract.stage,
            shortReason: contract.shortReason,
          },
          timestamp,
        };
        callbackRefs.current.onStep?.(step);
        return {
          ...prev,
          error: contract.displayMessage,
          isRunning: false,
          isAutoFixing: false,
          steps: [...prev.steps, step],
          operatorTimeline: [
            ...prev.operatorTimeline,
            {
              id: `terminal-failure-timeline-${timestamp}`,
              eventType,
              ts: timestamp,
              payload: event,
            },
          ].slice(-250),
        };
      }

      if (eventType === 'warning') {
        const warningStep: AgentStep = {
          id: `warning-${timestamp}`,
          type: 'thinking',
          content: String(event.message || 'Warning'),
          timestamp,
        };
        callbackRefs.current.onStep?.(warningStep);
        return {
          ...prev,
          steps: [...prev.steps, warningStep],
          operatorTimeline: [
            ...prev.operatorTimeline,
            {
              id: `warning-timeline-${timestamp}`,
              eventType,
              ts: timestamp,
              payload: event,
            },
          ].slice(-250),
        };
      }

      return prev;
    });
  }, []);

  const run = useCallback(async (
    prompt: string,
    initialFiles: Record<string, string> = {},
    initialPackages: string[] = [],
    options?: {
      mode?: PipelineMode; // Override auto-detection
      projectId?: string;
      userId?: string;
      tenantId?: string;
      persistRun?: boolean;
      builderContext?: BuilderContext;
      attachedImages?: string[]; // 🆕 Vision support: image URLs
    }
  ) => {
    console.log("[UnifiedOrchestrator] Starting:", prompt.slice(0, 50) + "...", "images:", options?.attachedImages?.length || 0);
    
    setState({
      ...initialState,
      isRunning: true,
      files: initialFiles,
      packages: initialPackages,
    });

    abortControllerRef.current = new AbortController();

    try {
      if (!isApiConfigured()) {
        throw new Error("API не настроен");
      }
      await runUnifiedOrchestratorStream(
        {
          prompt,
          files: initialFiles,
          packages: initialPackages,
          mode: options?.mode,
          projectId: options?.projectId,
          userId: options?.userId,
          tenantId: options?.tenantId,
          persistRun: options?.persistRun,
          builderContext: options?.builderContext,
          attachedImages: options?.attachedImages, // 🆕 Pass images for Vision
        },
        (event) => processEvent(event),
        {
          tenantId: options?.tenantId,
          signal: abortControllerRef.current.signal,
        }
      );

    } catch (err) {
      if (err instanceof Error && err.name === "AbortError") {
        console.log("[UnifiedOrchestrator] Request aborted by user");
        setState(prev => ({ ...prev, isRunning: false, isAutoFixing: false }));
        return;
      }

      const message = err instanceof Error ? err.message : "Unknown error occurred";
      console.error("[UnifiedOrchestrator] Error:", message, err);
      
      // 🆕 AUTO-RECOVERY: Check if we have a snapshot to recover from
      // This handles connection breaks, timeouts, and other stream errors
      const isConnectionError = message.includes('fetch') || 
                                message.includes('network') || 
                                message.includes('timeout') ||
                                message.includes('EPIPE') ||
                                message.includes('broken pipe') ||
                                err instanceof TypeError; // Network errors often throw TypeError
      
      setState(prev => {
        // If we have a recovery snapshot and it's a connection error, try auto-recovery
        if (prev.recoverySnapshotId && isConnectionError) {
          console.log('[UnifiedOrchestrator] Connection error detected; snapshot rollback requires server endpoint');
          return { 
            ...prev, 
            error: 'Соединение прервалось. Повтори запуск или восстанови файлы вручную.',
            isRunning: false, 
            isAutoFixing: false,
            isRecovering: false,
            completed: false,
          };
        }
        
        // No snapshot or not a connection error - just show the error
        return { 
          ...prev, 
          error: message, 
          isRunning: false, 
          isAutoFixing: false,
          completed: false,
        };
      });
      
      // Always call onError so the UI can react
      callbackRefs.current.onError?.(message);
    }
  }, [processEvent]);

  const stop = useCallback(() => {
    abortControllerRef.current?.abort();
    setState(prev => ({ ...prev, isRunning: false }));
  }, []);

  const reset = useCallback(() => {
    setState(initialState);
  }, []);

  // Migration approval/rejection with backend call
  const approveMigration = useCallback(async () => {
    const migration = state.pendingMigration;
    if (!migration) return;

    console.log('[UnifiedOrchestrator] Approving migration:', migration.id);
    
    // Set status to executing
    setState(prev => ({
      ...prev,
      pendingMigration: prev.pendingMigration 
        ? { ...prev.pendingMigration, status: 'executing' } 
        : null,
    }));

    try {
      setState(prev => ({
        ...prev,
        pendingMigration: prev.pendingMigration 
          ? { 
              ...prev.pendingMigration, 
              status: 'failed',
              result: {
                success: false,
                message: 'API migration executor is not implemented in this runtime',
              }
            } 
          : null,
      }));
      callbackRefs.current.onError?.('Migration executor is not implemented in API runtime');
    } catch (err) {
      console.error('[UnifiedOrchestrator] Migration execution error:', err);
      const errorMsg = err instanceof Error ? err.message : 'Migration execution failed';
      
      setState(prev => ({
        ...prev,
        pendingMigration: prev.pendingMigration 
          ? { 
              ...prev.pendingMigration, 
              status: 'failed',
              result: { success: false, message: errorMsg }
            } 
          : null,
      }));
      
      callbackRefs.current.onError?.(errorMsg);
    }
  }, [state.pendingMigration]);

  const rejectMigration = useCallback(async () => {
    const migration = state.pendingMigration;
    if (!migration) return;

    console.log('[UnifiedOrchestrator] Rejecting migration:', migration.id);
    
    setState(prev => ({
      ...prev,
      pendingMigration: prev.pendingMigration 
        ? { ...prev.pendingMigration, status: 'rejected' } 
        : null,
    }));

    try {
      // No-op in API-only mode until migration endpoint is implemented.
      return;
    } catch (err) {
      console.error('[UnifiedOrchestrator] Migration rejection error:', err);
    }
  }, [state.pendingMigration]);

  // 🆕 Recover from snapshot
  const recoverFromSnapshot = useCallback(async (snapshotId: string): Promise<{
    success: boolean;
    files: Record<string, string>;
    error?: string;
  }> => {
    console.log('[UnifiedOrchestrator] 🔄 Recovering from snapshot:', snapshotId);
    
    setState(prev => ({ ...prev, isRecovering: true }));
    
    try {
      setState(prev => ({ 
        ...prev, 
        isRecovering: false,
        error: null,
      }));

      return {
        success: false,
        files: {},
        error: 'Snapshot rollback endpoint is not implemented in API runtime',
      };
    } catch (error) {
      console.error('[UnifiedOrchestrator] ❌ Recovery failed:', error);
      
      setState(prev => ({ ...prev, isRecovering: false }));
      
      return {
        success: false,
        files: {},
        error: error instanceof Error ? error.message : 'Recovery failed',
      };
    }
  }, []);

  return {
    ...state,
    run,
    stop,
    reset,
    approveMigration,
    rejectMigration,
    recoverFromSnapshot, // 🆕 Expose recovery function
  };
}
